const template = {
  ID: "",
  name: " Wellness",
  objCode: "PRGM",
  projects: [
    {
      ID: "",
      name: " Engagement Project",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Engagement Project",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Implementation",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Internal Meetings",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Customer calls",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Production",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Producer Time",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Internal Sync",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Complete Data Sheet",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Update Data Sheet",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Create Design Brief and Notify Producer of Completion",
          objCode: "TASK",
          wbs: "1.2.5",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Communication Strategy",
          objCode: "TASK",
          wbs: "1.3",
          taskNumber: 11,
        },
        {
          ID: "",
          name: "Customer Comms Meeting",
          objCode: "TASK",
          wbs: "1.3.1",
          taskNumber: 12,
        },
        {
          ID: "",
          name: "Comms Strategy Planning",
          objCode: "TASK",
          wbs: "1.3.2",
          taskNumber: 13,
        },
      ],
      parameterValues: {
        "DE:Element": "Engagement Project",
        "DE:SKU#": "ENGAGE",
        "DE:Sales Force Account ID": "0000",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "Not an asset",
        "DE:To Translation Services?": "Not Applicable",
        "DE:Asset Status": "Not Applicable",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN079 Tobacco Cessation",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Digital Doc",
        "DE:SKU#": "BEN079",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN078 Nutrition & Exercise",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Infographics",
        "DE:SKU#": "BEN078",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN095 Helpful Wellness Resources",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Digital Doc",
        "DE:SKU#": "BEN095",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN097 Habits Worksheet",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Digital Doc",
        "DE:SKU#": "BEN097",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN081 Wellness Program Introduction",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Video",
        "DE:SKU#": "BEN081",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN082 Activities & Challenges",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Video",
        "DE:SKU#": "BEN082",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN085 Know Your Numbers",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Infographics",
        "DE:SKU#": "BEN085",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN075 Our Wellness Philosophy",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Video",
        "DE:SKU#": "BEN075",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN084 Checklist & Important Dates",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Digital Doc",
        "DE:SKU#": "BEN084",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN076 The Benefits of Prevention",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Video",
        "DE:SKU#": "BEN076",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN077 Healthy Habits",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Video",
        "DE:SKU#": "BEN077",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN083 Incentives & Rewards",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Element": "Digital Doc",
        "DE:SKU#": "BEN083",
        "DE:COGS?": "Yes",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "New",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
      },
    },
  ],
};

const actual = {
  ID: "",
  name: " Wellness",
  objCode: "PRGM",
  projects: [
    {
      ID: "",
      name: " Engagement Project",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Engagement Project",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Implementation",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Internal Meetings",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Customer calls",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Production",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Producer Time",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Internal Sync",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Complete Data Sheet",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Update Data Sheet",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Create Design Brief and Notify Producer of Completion",
          objCode: "TASK",
          wbs: "1.2.5",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Communication Strategy",
          objCode: "TASK",
          wbs: "1.3",
          taskNumber: 11,
        },
        {
          ID: "",
          name: "Customer Comms Meeting",
          objCode: "TASK",
          wbs: "1.3.1",
          taskNumber: 12,
        },
        {
          ID: "",
          name: "Comms Strategy Planning",
          objCode: "TASK",
          wbs: "1.3.2",
          taskNumber: 13,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "ENGAGE",
        "DE:Sales Force Account ID": "0000",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Company Name": "Tivian",
        "DE:Asset Cycle": "Not an asset",
        "DE:To Translation Services?": "Not Applicable",
        "DE:Asset Status": "Not Applicable",
        "DE:Customer Hard Deadline": "2023-06-30",
        "DE:Hours Category": "COGS",
      },
    },
    {
      ID: "",
      name: " BEN079 Tobacco Cessation",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN079",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Digital Doc",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN078 Nutrition & Exercise",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN078",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Infographics",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN095 Helpful Wellness Resources",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN095",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Digital Doc",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN097 Habits Worksheet",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN097",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Digital Doc",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN081 Wellness Program Introduction",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN081",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 14,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Video",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN082 Activities & Challenges",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN082",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 14,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Video",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN085 Know Your Numbers",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN085",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Infographics",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN075 Our Wellness Philosophy",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN075",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 14,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Video",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN084 Checklist & Important Dates",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN084",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Digital Doc",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN076 The Benefits of Prevention",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN076",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 14,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Video",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN077 Healthy Habits",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1: Voice Over",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2: Voice Over",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN077",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 14,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Video",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "AE (Templatized)",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
    {
      ID: "",
      name: " BEN083 Incentives & Rewards",
      objCode: "PROJ",
      tasks: [
        {
          ID: "",
          name: "Asset Creation",
          objCode: "TASK",
          wbs: "1",
          taskNumber: 1,
        },
        {
          ID: "",
          name: "Draft #1",
          objCode: "TASK",
          wbs: "1.1",
          taskNumber: 2,
        },
        {
          ID: "",
          name: "Writing Phase #1",
          objCode: "TASK",
          wbs: "1.1.1",
          taskNumber: 3,
        },
        {
          ID: "",
          name: "Asset Phase #1",
          objCode: "TASK",
          wbs: "1.1.2",
          taskNumber: 4,
        },
        {
          ID: "",
          name: "Design Phase #1",
          objCode: "TASK",
          wbs: "1.1.3",
          taskNumber: 5,
        },
        {
          ID: "",
          name: "Customer Review",
          objCode: "TASK",
          wbs: "1.1.4",
          taskNumber: 6,
        },
        {
          ID: "",
          name: "Draft #2",
          objCode: "TASK",
          wbs: "1.2",
          taskNumber: 7,
        },
        {
          ID: "",
          name: "Writing Phase #2",
          objCode: "TASK",
          wbs: "1.2.1",
          taskNumber: 8,
        },
        {
          ID: "",
          name: "Asset Phase #2",
          objCode: "TASK",
          wbs: "1.2.2",
          taskNumber: 9,
        },
        {
          ID: "",
          name: "Design Phase #2",
          objCode: "TASK",
          wbs: "1.2.3",
          taskNumber: 10,
        },
        {
          ID: "",
          name: "Customer Approval",
          objCode: "TASK",
          wbs: "1.2.4",
          taskNumber: 11,
        },
      ],
      parameterValues: {
        "DE:Producer/Project Owner": "Work Wizard",
        "DE:SKU#": "BEN083",
        "DE:COGS?": "Yes",
        "DE:Art Director": "Lauren Dubsky",
        "DE:Days Past HD": 8,
        "DE:Asset Cycle": "New",
        "DE:Asset Status": "Inactive",
        "DE:Hours Category": "COGS",
        "DE:Element": "Digital Doc",
        "DE:Company Name": "Tivian",
        "DE:Production Tool": "Asset Creation",
        "DE:To Translation Services?": "No",
        "DE:Customer Hard Deadline": "2023-06-30",
      },
    },
  ],
};
